name: Build and Release

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*' # Jalan saat ada push tag seperti v0.1.0
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-deb:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dibutuhkan untuk membuat release

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential liblzma-dev

    - name: Install cargo-deb
      run: cargo install cargo-deb

    - name: Build and Package
      run: cargo deb

    - name: Upload .deb Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lazarus_amd64.deb
        path: target/debian/*.deb

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: target/debian/*.deb
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}